name: Upload JSONs to S3

on:
  push:
    paths:
      - 'flashcard-jsons/**/*.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files to upload
        run: ls -R flashcard-jsons

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JSON files to S3
        run: aws s3 sync flashcard-jsons/ s3://snaportho-practice/flashcard-jsons/ --delete --acl public-read
